### ISSUE TITLE
MVP Integration

### ISSUE THREAD

**Issue by Ishaan-Datta** [UBCAgroBot/ROS#25]
Stage 1:  Bare Minimum Python Implementation (Ultralytics API) -> Testing on Oct 26th

- [x] !!! under examples/ROS2 Yolo Nodes there should be a template for exactly what you need to do
- [x] Load the model and run inference using the API (in the appropriate nodes)
- [x] Preprocessing should be automatic assuming you specify the input size
- [x] Postprocessing should automatically scale the bounding boxes and can save them as an object you can work with
- [x] Create custom message so we can pass the postprocessed camera input and velocity to the extermination node
- [x] On the extermination node:  Draw bounding boxes on orignal image so we can output it.
- [ ] Make a script for recording Zed frames as pictures in a folder for data collection
- [x] Apply the ROI shift using velocity before cropping picture to ROI in preprocessing stage
- [x] Post-processing (crop the image to the resized bounding boxes and pass them through the color filter for more accurate boxes)
- [x] (check if the more accurate boxes are within the scaled ROI (sprayer area) and publish 1 or 0 every 0.10 seconds)
- [ ] Ask for code later for serializing messages to USB using pyserial
- [x] create README.md for installing/running rviz with launch file
- [ ] create README.md for parameters and usage of launch files

Stage 2: C++ Foundations -> Testing on March 8th

- [ ] Split the Node functionality into modules
- [ ] Copy [example](https://github.com/stereolabs/zed-multi-camera) for working with multiple cameras

Stage 3: C++ Optimizations -> Testing on May 3rd
ROS2 Specific Features: (with Aqil)

- [ ] Integrated Tracing
- [ ] Custom Message Types
- [ ] Composable Containers/Intra-Process Communication
- [ ] Multi-threaded Executor

CUDA Specific Features: (with Kezia)

- [ ] Implement best performing CUDA operations/TensorRT Engine Plugins

Model Specific Features: (with Amy)

- [ ] Implement best performing converted TensorRT Engine
- [ ] Implement Ultralytics Examples for C++ TensorRT Inference (/examples/YOLOV8-*)
- [ ] Implement Nvidia Examples for C++ TensorRT Inference [Google Drive](https://drive.google.com/drive/folders/1VhBxbrtv_gMllZ_UmPlYBvmKxV4Yi8Fn?usp=sharing)

**Comment by vangeliq** [comment]
https://www.patterns.dev/vanilla/singleton-pattern/ for the util class
