### ISSUE TITLE
ROS Package Repairs

### ISSUE THREAD

**Issue by Ishaan-Datta** [UBCAgroBot/ROS#34]
- [x] setup nomachine (and make it work hopefully)
- [x] document where colcon build needs to happen (should be inside ros2_ws?)
- [x] fix the ~/.bashrc terminal to make sure it sources the correct install/source.sh -> or was it local_setup.sh? idr
- [x] fix the relative paths to absolute (will fix hardcoding the root to work on any system relative to directory base)
- [x] make launch files with appropriate parameters passing

**Comment by vangeliq** [comment]
@Ishaan-Datta which branch should I base this issue on?

**Comment by vangeliq** [comment]
And what does “fix the relative paths to absolute (will fix hardcoding the root to work on any system relative to directory base” entail? Are we wanting to make it hardcoded or always relative to the repository root directory?
